# Each new term in the Fibonacci sequence is generated by adding the previous two
# terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

i = 0
total = 2
x = 2
y = 3
z = 0
for i in range(0, 900):
    if(x < 4000001 and y < 4000001):

        if(y % 2) == 0:
            total = total + y
            #print("y total:", y, "|", "total:", total)
        #print(x, y)

        z = x
        x = y
        y = y + z

print(total)
